name: sentry_experiment
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ">=3.0.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sentry_flutter: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  sentry_dart_plugin: ^1.3.0

flutter:
  uses-material-design: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  project: sentry-exp
  org: experiment-0v
  auth_token: de6204634e484e5daa6a935cc67831a21cba74a3aba54f9182a4497ca5d1ec15
  url: https://697d64dbdae4493c8a0254a3b469be53@o4505358017101824.ingest.sentry.io
  release: sentry-exp@1.0.0+7
  wait_for_processing: true
  log_level: error
  commits: auto
  ignore_missing: true

# sentry:
#   upload_debug_symbols: true
#   upload_source_maps: true
#   upload_sources: true
#   project: qa
#   org: vepo-ut
#   auth_token: my_secret_auth_token
#   release: vepo@0.0.2+1
#   wait_for_processing: true
#   log_level: error
#   commits: auto
#   ignore_missing: true